/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const CreatePickupInput = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const DriverProfilePublic = IDL.Record({
  'id' : UserId,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'photoKey' : IDL.Opt(IDL.Text),
  'bloodGroup' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DutyStatus = IDL.Variant({
  'offDuty' : IDL.Null,
  'onDuty' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const GpsLocationPublic = IDL.Record({
  'latitude' : IDL.Float64,
  'active' : IDL.Bool,
  'longitude' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const DriverStatePublic = IDL.Record({
  'id' : UserId,
  'dutyStatus' : DutyStatus,
  'fillPercent' : IDL.Nat,
  'location' : IDL.Opt(GpsLocationPublic),
});
export const MessagePublic = IDL.Record({
  'id' : IDL.Nat,
  'read' : IDL.Bool,
  'text' : IDL.Text,
  'receiverId' : UserId,
  'timestamp' : Timestamp,
  'senderId' : UserId,
});
export const PickupStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PickupRequestPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : PickupStatus,
  'latitude' : IDL.Float64,
  'driverId' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'customerId' : UserId,
});
export const Role = IDL.Variant({
  'customer' : IDL.Null,
  'owner' : IDL.Null,
  'driver' : IDL.Null,
});
export const VehiclePublic = IDL.Record({
  'id' : IDL.Nat,
  'vehicleNumber' : IDL.Text,
  'assignedDriverId' : IDL.Opt(UserId),
  'makeModel' : IDL.Text,
});
export const ComplaintCategory = IDL.Variant({
  'driverBehavior' : IDL.Null,
  'other' : IDL.Text,
  'missedPickup' : IDL.Null,
  'vehicleCondition' : IDL.Null,
});
export const ComplaintPublic = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Timestamp,
  'category' : ComplaintCategory,
  'customerId' : UserId,
});
export const TipProvider = IDL.Variant({
  'other' : IDL.Text,
  'gPay' : IDL.Null,
  'postOfficeSavings' : IDL.Null,
  'paytm' : IDL.Null,
  'phonePe' : IDL.Null,
});
export const TipPublic = IDL.Record({
  'id' : IDL.Nat,
  'driverId' : UserId,
  'provider' : TipProvider,
  'timestamp' : Timestamp,
  'customerId' : UserId,
  'amount' : IDL.Nat,
});
export const RegisterResult = IDL.Variant({
  'ok' : UserId,
  'alreadyExists' : IDL.Null,
});
export const SubmitComplaintInput = IDL.Record({
  'text' : IDL.Text,
  'category' : ComplaintCategory,
});
export const SubmitTipInput = IDL.Record({
  'driverId' : UserId,
  'provider' : TipProvider,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'acceptPickupRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'addVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(UserId)], [IDL.Nat], []),
  'assignDriver' : IDL.Func([IDL.Nat, IDL.Opt(UserId)], [], []),
  'createPickupRequest' : IDL.Func([CreatePickupInput], [IDL.Nat], []),
  'getDriverProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(DriverProfilePublic)],
      ['query'],
    ),
  'getDriverState' : IDL.Func(
      [UserId],
      [IDL.Opt(DriverStatePublic)],
      ['query'],
    ),
  'getMessageThread' : IDL.Func([UserId], [IDL.Vec(MessagePublic)], ['query']),
  'getMyPickupRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PickupRequestPublic)],
      ['query'],
    ),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(VehiclePublic)], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPickupRequests' : IDL.Func(
      [],
      [IDL.Vec(PickupRequestPublic)],
      ['query'],
    ),
  'listComplaints' : IDL.Func([], [IDL.Vec(ComplaintPublic)], ['query']),
  'listDriverProfiles' : IDL.Func(
      [],
      [IDL.Vec(DriverProfilePublic)],
      ['query'],
    ),
  'listDriverStates' : IDL.Func([], [IDL.Vec(DriverStatePublic)], ['query']),
  'listMyPickupRequests' : IDL.Func(
      [],
      [IDL.Vec(PickupRequestPublic)],
      ['query'],
    ),
  'listMyTips' : IDL.Func([], [IDL.Vec(TipPublic)], ['query']),
  'listPendingPickupRequests' : IDL.Func(
      [],
      [IDL.Vec(PickupRequestPublic)],
      ['query'],
    ),
  'listVehicles' : IDL.Func([], [IDL.Vec(VehiclePublic)], ['query']),
  'markThreadRead' : IDL.Func([UserId], [], []),
  'register' : IDL.Func([Role, IDL.Text], [RegisterResult], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
  'setDutyStatus' : IDL.Func([DutyStatus], [], []),
  'setFillPercent' : IDL.Func([IDL.Nat], [], []),
  'submitComplaint' : IDL.Func([SubmitComplaintInput], [IDL.Nat], []),
  'submitTip' : IDL.Func([SubmitTipInput], [IDL.Nat], []),
  'unreadMessageCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'updateLocation' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Bool], [], []),
  'updatePickupStatus' : IDL.Func([IDL.Nat, PickupStatus], [IDL.Bool], []),
  'upsertDriverProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const CreatePickupInput = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const DriverProfilePublic = IDL.Record({
    'id' : UserId,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'photoKey' : IDL.Opt(IDL.Text),
    'bloodGroup' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DutyStatus = IDL.Variant({ 'offDuty' : IDL.Null, 'onDuty' : IDL.Null });
  const Timestamp = IDL.Int;
  const GpsLocationPublic = IDL.Record({
    'latitude' : IDL.Float64,
    'active' : IDL.Bool,
    'longitude' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const DriverStatePublic = IDL.Record({
    'id' : UserId,
    'dutyStatus' : DutyStatus,
    'fillPercent' : IDL.Nat,
    'location' : IDL.Opt(GpsLocationPublic),
  });
  const MessagePublic = IDL.Record({
    'id' : IDL.Nat,
    'read' : IDL.Bool,
    'text' : IDL.Text,
    'receiverId' : UserId,
    'timestamp' : Timestamp,
    'senderId' : UserId,
  });
  const PickupStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PickupRequestPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : PickupStatus,
    'latitude' : IDL.Float64,
    'driverId' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'customerId' : UserId,
  });
  const Role = IDL.Variant({
    'customer' : IDL.Null,
    'owner' : IDL.Null,
    'driver' : IDL.Null,
  });
  const VehiclePublic = IDL.Record({
    'id' : IDL.Nat,
    'vehicleNumber' : IDL.Text,
    'assignedDriverId' : IDL.Opt(UserId),
    'makeModel' : IDL.Text,
  });
  const ComplaintCategory = IDL.Variant({
    'driverBehavior' : IDL.Null,
    'other' : IDL.Text,
    'missedPickup' : IDL.Null,
    'vehicleCondition' : IDL.Null,
  });
  const ComplaintPublic = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Timestamp,
    'category' : ComplaintCategory,
    'customerId' : UserId,
  });
  const TipProvider = IDL.Variant({
    'other' : IDL.Text,
    'gPay' : IDL.Null,
    'postOfficeSavings' : IDL.Null,
    'paytm' : IDL.Null,
    'phonePe' : IDL.Null,
  });
  const TipPublic = IDL.Record({
    'id' : IDL.Nat,
    'driverId' : UserId,
    'provider' : TipProvider,
    'timestamp' : Timestamp,
    'customerId' : UserId,
    'amount' : IDL.Nat,
  });
  const RegisterResult = IDL.Variant({
    'ok' : UserId,
    'alreadyExists' : IDL.Null,
  });
  const SubmitComplaintInput = IDL.Record({
    'text' : IDL.Text,
    'category' : ComplaintCategory,
  });
  const SubmitTipInput = IDL.Record({
    'driverId' : UserId,
    'provider' : TipProvider,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'acceptPickupRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'addVehicle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(UserId)],
        [IDL.Nat],
        [],
      ),
    'assignDriver' : IDL.Func([IDL.Nat, IDL.Opt(UserId)], [], []),
    'createPickupRequest' : IDL.Func([CreatePickupInput], [IDL.Nat], []),
    'getDriverProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(DriverProfilePublic)],
        ['query'],
      ),
    'getDriverState' : IDL.Func(
        [UserId],
        [IDL.Opt(DriverStatePublic)],
        ['query'],
      ),
    'getMessageThread' : IDL.Func(
        [UserId],
        [IDL.Vec(MessagePublic)],
        ['query'],
      ),
    'getMyPickupRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PickupRequestPublic)],
        ['query'],
      ),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(VehiclePublic)], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPickupRequests' : IDL.Func(
        [],
        [IDL.Vec(PickupRequestPublic)],
        ['query'],
      ),
    'listComplaints' : IDL.Func([], [IDL.Vec(ComplaintPublic)], ['query']),
    'listDriverProfiles' : IDL.Func(
        [],
        [IDL.Vec(DriverProfilePublic)],
        ['query'],
      ),
    'listDriverStates' : IDL.Func([], [IDL.Vec(DriverStatePublic)], ['query']),
    'listMyPickupRequests' : IDL.Func(
        [],
        [IDL.Vec(PickupRequestPublic)],
        ['query'],
      ),
    'listMyTips' : IDL.Func([], [IDL.Vec(TipPublic)], ['query']),
    'listPendingPickupRequests' : IDL.Func(
        [],
        [IDL.Vec(PickupRequestPublic)],
        ['query'],
      ),
    'listVehicles' : IDL.Func([], [IDL.Vec(VehiclePublic)], ['query']),
    'markThreadRead' : IDL.Func([UserId], [], []),
    'register' : IDL.Func([Role, IDL.Text], [RegisterResult], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
    'setDutyStatus' : IDL.Func([DutyStatus], [], []),
    'setFillPercent' : IDL.Func([IDL.Nat], [], []),
    'submitComplaint' : IDL.Func([SubmitComplaintInput], [IDL.Nat], []),
    'submitTip' : IDL.Func([SubmitTipInput], [IDL.Nat], []),
    'unreadMessageCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'updateLocation' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Bool], [], []),
    'updatePickupStatus' : IDL.Func([IDL.Nat, PickupStatus], [IDL.Bool], []),
    'upsertDriverProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };