/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ComplaintCategory = { 'driverBehavior' : null } |
  { 'other' : string } |
  { 'missedPickup' : null } |
  { 'vehicleCondition' : null };
export interface ComplaintPublic {
  'id' : bigint,
  'text' : string,
  'timestamp' : Timestamp,
  'category' : ComplaintCategory,
  'customerId' : UserId,
}
export interface CreatePickupInput {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export interface DriverProfilePublic {
  'id' : UserId,
  'age' : bigint,
  'name' : string,
  'photoKey' : [] | [string],
  'bloodGroup' : string,
  'address' : string,
  'phone' : string,
}
export interface DriverStatePublic {
  'id' : UserId,
  'dutyStatus' : DutyStatus,
  'fillPercent' : bigint,
  'location' : [] | [GpsLocationPublic],
}
export type DutyStatus = { 'offDuty' : null } |
  { 'onDuty' : null };
export interface GpsLocationPublic {
  'latitude' : number,
  'active' : boolean,
  'longitude' : number,
  'timestamp' : Timestamp,
}
export interface MessagePublic {
  'id' : bigint,
  'read' : boolean,
  'text' : string,
  'receiverId' : UserId,
  'timestamp' : Timestamp,
  'senderId' : UserId,
}
export interface PickupRequestPublic {
  'id' : bigint,
  'status' : PickupStatus,
  'latitude' : number,
  'driverId' : [] | [UserId],
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'longitude' : number,
  'address' : string,
  'customerId' : UserId,
}
export type PickupStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export type RegisterResult = { 'ok' : UserId } |
  { 'alreadyExists' : null };
export type Role = { 'customer' : null } |
  { 'owner' : null } |
  { 'driver' : null };
export interface SubmitComplaintInput {
  'text' : string,
  'category' : ComplaintCategory,
}
export interface SubmitTipInput {
  'driverId' : UserId,
  'provider' : TipProvider,
  'amount' : bigint,
}
export type Timestamp = bigint;
export type TipProvider = { 'other' : string } |
  { 'gPay' : null } |
  { 'postOfficeSavings' : null } |
  { 'paytm' : null } |
  { 'phonePe' : null };
export interface TipPublic {
  'id' : bigint,
  'driverId' : UserId,
  'provider' : TipProvider,
  'timestamp' : Timestamp,
  'customerId' : UserId,
  'amount' : bigint,
}
export type UserId = Principal;
export interface VehiclePublic {
  'id' : bigint,
  'vehicleNumber' : string,
  'assignedDriverId' : [] | [UserId],
  'makeModel' : string,
}
export interface _SERVICE {
  'acceptPickupRequest' : ActorMethod<[bigint], boolean>,
  'addVehicle' : ActorMethod<[string, string, [] | [UserId]], bigint>,
  'assignDriver' : ActorMethod<[bigint, [] | [UserId]], undefined>,
  'createPickupRequest' : ActorMethod<[CreatePickupInput], bigint>,
  'getDriverProfile' : ActorMethod<[UserId], [] | [DriverProfilePublic]>,
  'getDriverState' : ActorMethod<[UserId], [] | [DriverStatePublic]>,
  'getMessageThread' : ActorMethod<[UserId], Array<MessagePublic>>,
  'getMyPickupRequest' : ActorMethod<[bigint], [] | [PickupRequestPublic]>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getVehicle' : ActorMethod<[bigint], [] | [VehiclePublic]>,
  'isRegistered' : ActorMethod<[], boolean>,
  'listAllPickupRequests' : ActorMethod<[], Array<PickupRequestPublic>>,
  'listComplaints' : ActorMethod<[], Array<ComplaintPublic>>,
  'listDriverProfiles' : ActorMethod<[], Array<DriverProfilePublic>>,
  'listDriverStates' : ActorMethod<[], Array<DriverStatePublic>>,
  'listMyPickupRequests' : ActorMethod<[], Array<PickupRequestPublic>>,
  'listMyTips' : ActorMethod<[], Array<TipPublic>>,
  'listPendingPickupRequests' : ActorMethod<[], Array<PickupRequestPublic>>,
  'listVehicles' : ActorMethod<[], Array<VehiclePublic>>,
  'markThreadRead' : ActorMethod<[UserId], undefined>,
  'register' : ActorMethod<[Role, string], RegisterResult>,
  'sendMessage' : ActorMethod<[UserId, string], bigint>,
  'setDutyStatus' : ActorMethod<[DutyStatus], undefined>,
  'setFillPercent' : ActorMethod<[bigint], undefined>,
  'submitComplaint' : ActorMethod<[SubmitComplaintInput], bigint>,
  'submitTip' : ActorMethod<[SubmitTipInput], bigint>,
  'unreadMessageCount' : ActorMethod<[UserId], bigint>,
  'updateLocation' : ActorMethod<[number, number, boolean], undefined>,
  'updatePickupStatus' : ActorMethod<[bigint, PickupStatus], boolean>,
  'upsertDriverProfile' : ActorMethod<
    [string, bigint, string, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];