/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MessagePublic {
    id: bigint;
    read: boolean;
    text: string;
    receiverId: UserId;
    timestamp: Timestamp;
    senderId: UserId;
}
export type Timestamp = bigint;
export interface VehiclePublic {
    id: bigint;
    vehicleNumber: string;
    assignedDriverId?: UserId;
    makeModel: string;
}
export interface SubmitComplaintInput {
    text: string;
    category: ComplaintCategory;
}
export interface PickupRequestPublic {
    id: bigint;
    status: PickupStatus;
    latitude: number;
    driverId?: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    longitude: number;
    address: string;
    customerId: UserId;
}
export type UserId = Principal;
export interface SubmitTipInput {
    driverId: UserId;
    provider: TipProvider;
    amount: bigint;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: UserId;
} | {
    __kind__: "alreadyExists";
    alreadyExists: null;
};
export interface CreatePickupInput {
    latitude: number;
    longitude: number;
    address: string;
}
export interface ComplaintPublic {
    id: bigint;
    text: string;
    timestamp: Timestamp;
    category: ComplaintCategory;
    customerId: UserId;
}
export type TipProvider = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "gPay";
    gPay: null;
} | {
    __kind__: "postOfficeSavings";
    postOfficeSavings: null;
} | {
    __kind__: "paytm";
    paytm: null;
} | {
    __kind__: "phonePe";
    phonePe: null;
};
export interface GpsLocationPublic {
    latitude: number;
    active: boolean;
    longitude: number;
    timestamp: Timestamp;
}
export type ComplaintCategory = {
    __kind__: "driverBehavior";
    driverBehavior: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "missedPickup";
    missedPickup: null;
} | {
    __kind__: "vehicleCondition";
    vehicleCondition: null;
};
export interface DriverProfilePublic {
    id: UserId;
    age: bigint;
    name: string;
    photoKey?: string;
    bloodGroup: string;
    address: string;
    phone: string;
}
export interface TipPublic {
    id: bigint;
    driverId: UserId;
    provider: TipProvider;
    timestamp: Timestamp;
    customerId: UserId;
    amount: bigint;
}
export interface DriverStatePublic {
    id: UserId;
    dutyStatus: DutyStatus;
    fillPercent: bigint;
    location?: GpsLocationPublic;
}
export enum DutyStatus {
    offDuty = "offDuty",
    onDuty = "onDuty"
}
export enum PickupStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted"
}
export enum Role {
    customer = "customer",
    owner = "owner",
    driver = "driver"
}
export interface backendInterface {
    acceptPickupRequest(requestId: bigint): Promise<boolean>;
    addVehicle(vehicleNumber: string, makeModel: string, assignedDriverId: UserId | null): Promise<bigint>;
    assignDriver(vehicleId: bigint, driverId: UserId | null): Promise<void>;
    createPickupRequest(input: CreatePickupInput): Promise<bigint>;
    getDriverProfile(driverId: UserId): Promise<DriverProfilePublic | null>;
    getDriverState(driverId: UserId): Promise<DriverStatePublic | null>;
    getMessageThread(otherId: UserId): Promise<Array<MessagePublic>>;
    getMyPickupRequest(requestId: bigint): Promise<PickupRequestPublic | null>;
    getMyRole(): Promise<Role | null>;
    getVehicle(id: bigint): Promise<VehiclePublic | null>;
    isRegistered(): Promise<boolean>;
    listAllPickupRequests(): Promise<Array<PickupRequestPublic>>;
    listComplaints(): Promise<Array<ComplaintPublic>>;
    listDriverProfiles(): Promise<Array<DriverProfilePublic>>;
    listDriverStates(): Promise<Array<DriverStatePublic>>;
    listMyPickupRequests(): Promise<Array<PickupRequestPublic>>;
    listMyTips(): Promise<Array<TipPublic>>;
    listPendingPickupRequests(): Promise<Array<PickupRequestPublic>>;
    listVehicles(): Promise<Array<VehiclePublic>>;
    markThreadRead(senderId: UserId): Promise<void>;
    register(role: Role, displayName: string): Promise<RegisterResult>;
    sendMessage(receiverId: UserId, text: string): Promise<bigint>;
    setDutyStatus(status: DutyStatus): Promise<void>;
    setFillPercent(percent: bigint): Promise<void>;
    submitComplaint(input: SubmitComplaintInput): Promise<bigint>;
    submitTip(input: SubmitTipInput): Promise<bigint>;
    unreadMessageCount(senderId: UserId): Promise<bigint>;
    updateLocation(latitude: number, longitude: number, active: boolean): Promise<void>;
    updatePickupStatus(requestId: bigint, status: PickupStatus): Promise<boolean>;
    upsertDriverProfile(name: string, age: bigint, phone: string, bloodGroup: string, address: string, photoKey: string | null): Promise<void>;
}
import type { ComplaintCategory as _ComplaintCategory, ComplaintPublic as _ComplaintPublic, DriverProfilePublic as _DriverProfilePublic, DriverStatePublic as _DriverStatePublic, DutyStatus as _DutyStatus, GpsLocationPublic as _GpsLocationPublic, PickupRequestPublic as _PickupRequestPublic, PickupStatus as _PickupStatus, RegisterResult as _RegisterResult, Role as _Role, SubmitComplaintInput as _SubmitComplaintInput, SubmitTipInput as _SubmitTipInput, Timestamp as _Timestamp, TipProvider as _TipProvider, TipPublic as _TipPublic, UserId as _UserId, VehiclePublic as _VehiclePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptPickupRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptPickupRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptPickupRequest(arg0);
            return result;
        }
    }
    async addVehicle(arg0: string, arg1: string, arg2: UserId | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignDriver(arg0: bigint, arg1: UserId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDriver(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDriver(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPickupRequest(arg0: CreatePickupInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPickupRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPickupRequest(arg0);
            return result;
        }
    }
    async getDriverProfile(arg0: UserId): Promise<DriverProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverProfile(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverProfile(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverState(arg0: UserId): Promise<DriverStatePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverState(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverState(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageThread(arg0: UserId): Promise<Array<MessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageThread(arg0);
            return result;
        }
    }
    async getMyPickupRequest(arg0: bigint): Promise<PickupRequestPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPickupRequest(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPickupRequest(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: bigint): Promise<VehiclePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async listAllPickupRequests(): Promise<Array<PickupRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPickupRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPickupRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listComplaints(): Promise<Array<ComplaintPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComplaints();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComplaints();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDriverProfiles(): Promise<Array<DriverProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDriverProfiles();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDriverProfiles();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDriverStates(): Promise<Array<DriverStatePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDriverStates();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDriverStates();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyPickupRequests(): Promise<Array<PickupRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyPickupRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyPickupRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyTips(): Promise<Array<TipPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyTips();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyTips();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingPickupRequests(): Promise<Array<PickupRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingPickupRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingPickupRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<VehiclePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async markThreadRead(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markThreadRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markThreadRead(arg0);
            return result;
        }
    }
    async register(arg0: Role, arg1: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_Role_n38(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_RegisterResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_Role_n38(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_RegisterResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setDutyStatus(arg0: DutyStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDutyStatus(to_candid_DutyStatus_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDutyStatus(to_candid_DutyStatus_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setFillPercent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFillPercent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFillPercent(arg0);
            return result;
        }
    }
    async submitComplaint(arg0: SubmitComplaintInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(to_candid_SubmitComplaintInput_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(to_candid_SubmitComplaintInput_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTip(arg0: SubmitTipInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTip(to_candid_SubmitTipInput_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTip(to_candid_SubmitTipInput_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unreadMessageCount(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.unreadMessageCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unreadMessageCount(arg0);
            return result;
        }
    }
    async updateLocation(arg0: number, arg1: number, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePickupStatus(arg0: bigint, arg1: PickupStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePickupStatus(arg0, to_candid_PickupStatus_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePickupStatus(arg0, to_candid_PickupStatus_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertDriverProfile(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertDriverProfile(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertDriverProfile(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_ComplaintCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintCategory): ComplaintCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ComplaintPublic_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintPublic): ComplaintPublic {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DriverProfilePublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverProfilePublic): DriverProfilePublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DriverStatePublic_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverStatePublic): DriverStatePublic {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DutyStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DutyStatus): DutyStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PickupRequestPublic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupRequestPublic): PickupRequestPublic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PickupStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupStatus): PickupStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TipProvider_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TipProvider): TipProvider {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_TipPublic_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TipPublic): TipPublic {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_VehiclePublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehiclePublic): VehiclePublic {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GpsLocationPublic]): GpsLocationPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PickupRequestPublic]): PickupRequestPublic | null {
    return value.length === 0 ? null : from_candid_PickupRequestPublic_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverProfilePublic]): DriverProfilePublic | null {
    return value.length === 0 ? null : from_candid_DriverProfilePublic_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehiclePublic]): VehiclePublic | null {
    return value.length === 0 ? null : from_candid_VehiclePublic_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverStatePublic]): DriverStatePublic | null {
    return value.length === 0 ? null : from_candid_DriverStatePublic_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PickupStatus;
    latitude: number;
    driverId: [] | [_UserId];
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    longitude: number;
    address: string;
    customerId: _UserId;
}): {
    id: bigint;
    status: PickupStatus;
    latitude: number;
    driverId?: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    longitude: number;
    address: string;
    customerId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_PickupStatus_n15(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        driverId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.driverId)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        longitude: value.longitude,
        address: value.address,
        customerId: value.customerId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    vehicleNumber: string;
    assignedDriverId: [] | [_UserId];
    makeModel: string;
}): {
    id: bigint;
    vehicleNumber: string;
    assignedDriverId?: UserId;
    makeModel: string;
} {
    return {
        id: value.id,
        vehicleNumber: value.vehicleNumber,
        assignedDriverId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedDriverId)),
        makeModel: value.makeModel
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    timestamp: _Timestamp;
    category: _ComplaintCategory;
    customerId: _UserId;
}): {
    id: bigint;
    text: string;
    timestamp: Timestamp;
    category: ComplaintCategory;
    customerId: UserId;
} {
    return {
        id: value.id,
        text: value.text,
        timestamp: value.timestamp,
        category: from_candid_ComplaintCategory_n28(_uploadFile, _downloadFile, value.category),
        customerId: value.customerId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    driverId: _UserId;
    provider: _TipProvider;
    timestamp: _Timestamp;
    customerId: _UserId;
    amount: bigint;
}): {
    id: bigint;
    driverId: UserId;
    provider: TipProvider;
    timestamp: Timestamp;
    customerId: UserId;
    amount: bigint;
} {
    return {
        id: value.id,
        driverId: value.driverId,
        provider: from_candid_TipProvider_n35(_uploadFile, _downloadFile, value.provider),
        timestamp: value.timestamp,
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    age: bigint;
    name: string;
    photoKey: [] | [string];
    bloodGroup: string;
    address: string;
    phone: string;
}): {
    id: UserId;
    age: bigint;
    name: string;
    photoKey?: string;
    bloodGroup: string;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        age: value.age,
        name: value.name,
        photoKey: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.photoKey)),
        bloodGroup: value.bloodGroup,
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    dutyStatus: _DutyStatus;
    fillPercent: bigint;
    location: [] | [_GpsLocationPublic];
}): {
    id: UserId;
    dutyStatus: DutyStatus;
    fillPercent: bigint;
    location?: GpsLocationPublic;
} {
    return {
        id: value.id,
        dutyStatus: from_candid_DutyStatus_n9(_uploadFile, _downloadFile, value.dutyStatus),
        fillPercent: value.fillPercent,
        location: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offDuty: null;
} | {
    onDuty: null;
}): DutyStatus {
    return "offDuty" in value ? DutyStatus.offDuty : "onDuty" in value ? DutyStatus.onDuty : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
}): PickupStatus {
    return "cancelled" in value ? PickupStatus.cancelled : "pending" in value ? PickupStatus.pending : "completed" in value ? PickupStatus.completed : "accepted" in value ? PickupStatus.accepted : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    owner: null;
} | {
    driver: null;
}): Role {
    return "customer" in value ? Role.customer : "owner" in value ? Role.owner : "driver" in value ? Role.driver : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    driverBehavior: null;
} | {
    other: string;
} | {
    missedPickup: null;
} | {
    vehicleCondition: null;
}): {
    __kind__: "driverBehavior";
    driverBehavior: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "missedPickup";
    missedPickup: null;
} | {
    __kind__: "vehicleCondition";
    vehicleCondition: null;
} {
    return "driverBehavior" in value ? {
        __kind__: "driverBehavior",
        driverBehavior: value.driverBehavior
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "missedPickup" in value ? {
        __kind__: "missedPickup",
        missedPickup: value.missedPickup
    } : "vehicleCondition" in value ? {
        __kind__: "vehicleCondition",
        vehicleCondition: value.vehicleCondition
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    gPay: null;
} | {
    postOfficeSavings: null;
} | {
    paytm: null;
} | {
    phonePe: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "gPay";
    gPay: null;
} | {
    __kind__: "postOfficeSavings";
    postOfficeSavings: null;
} | {
    __kind__: "paytm";
    paytm: null;
} | {
    __kind__: "phonePe";
    phonePe: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "gPay" in value ? {
        __kind__: "gPay",
        gPay: value.gPay
    } : "postOfficeSavings" in value ? {
        __kind__: "postOfficeSavings",
        postOfficeSavings: value.postOfficeSavings
    } : "paytm" in value ? {
        __kind__: "paytm",
        paytm: value.paytm
    } : "phonePe" in value ? {
        __kind__: "phonePe",
        phonePe: value.phonePe
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserId;
} | {
    alreadyExists: null;
}): {
    __kind__: "ok";
    ok: UserId;
} | {
    __kind__: "alreadyExists";
    alreadyExists: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "alreadyExists" in value ? {
        __kind__: "alreadyExists",
        alreadyExists: value.alreadyExists
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PickupRequestPublic>): Array<PickupRequestPublic> {
    return value.map((x)=>from_candid_PickupRequestPublic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComplaintPublic>): Array<ComplaintPublic> {
    return value.map((x)=>from_candid_ComplaintPublic_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DriverProfilePublic>): Array<DriverProfilePublic> {
    return value.map((x)=>from_candid_DriverProfilePublic_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DriverStatePublic>): Array<DriverStatePublic> {
    return value.map((x)=>from_candid_DriverStatePublic_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TipPublic>): Array<TipPublic> {
    return value.map((x)=>from_candid_TipPublic_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehiclePublic>): Array<VehiclePublic> {
    return value.map((x)=>from_candid_VehiclePublic_n22(_uploadFile, _downloadFile, x));
}
function to_candid_ComplaintCategory_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintCategory): _ComplaintCategory {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_DutyStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DutyStatus): _DutyStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_PickupStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupStatus): _PickupStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitComplaintInput_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitComplaintInput): _SubmitComplaintInput {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitTipInput_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitTipInput): _SubmitTipInput {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_TipProvider_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TipProvider): _TipProvider {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    category: ComplaintCategory;
}): {
    text: string;
    category: _ComplaintCategory;
} {
    return {
        text: value.text,
        category: to_candid_ComplaintCategory_n46(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    driverId: UserId;
    provider: TipProvider;
    amount: bigint;
}): {
    driverId: _UserId;
    provider: _TipProvider;
    amount: bigint;
} {
    return {
        driverId: value.driverId,
        provider: to_candid_TipProvider_n50(_uploadFile, _downloadFile, value.provider),
        amount: value.amount
    };
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    customer: null;
} | {
    owner: null;
} | {
    driver: null;
} {
    return value == Role.customer ? {
        customer: null
    } : value == Role.owner ? {
        owner: null
    } : value == Role.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DutyStatus): {
    offDuty: null;
} | {
    onDuty: null;
} {
    return value == DutyStatus.offDuty ? {
        offDuty: null
    } : value == DutyStatus.onDuty ? {
        onDuty: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "driverBehavior";
    driverBehavior: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "missedPickup";
    missedPickup: null;
} | {
    __kind__: "vehicleCondition";
    vehicleCondition: null;
}): {
    driverBehavior: null;
} | {
    other: string;
} | {
    missedPickup: null;
} | {
    vehicleCondition: null;
} {
    return value.__kind__ === "driverBehavior" ? {
        driverBehavior: value.driverBehavior
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "missedPickup" ? {
        missedPickup: value.missedPickup
    } : value.__kind__ === "vehicleCondition" ? {
        vehicleCondition: value.vehicleCondition
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "gPay";
    gPay: null;
} | {
    __kind__: "postOfficeSavings";
    postOfficeSavings: null;
} | {
    __kind__: "paytm";
    paytm: null;
} | {
    __kind__: "phonePe";
    phonePe: null;
}): {
    other: string;
} | {
    gPay: null;
} | {
    postOfficeSavings: null;
} | {
    paytm: null;
} | {
    phonePe: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "gPay" ? {
        gPay: value.gPay
    } : value.__kind__ === "postOfficeSavings" ? {
        postOfficeSavings: value.postOfficeSavings
    } : value.__kind__ === "paytm" ? {
        paytm: value.paytm
    } : value.__kind__ === "phonePe" ? {
        phonePe: value.phonePe
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} {
    return value == PickupStatus.cancelled ? {
        cancelled: null
    } : value == PickupStatus.pending ? {
        pending: null
    } : value == PickupStatus.completed ? {
        completed: null
    } : value == PickupStatus.accepted ? {
        accepted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
